default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: budget_manager_dev
  username: sagie
  password: password
  host: localhost

test:
  <<: *default
  database: budget_manager_test
  username: sagie
  password: password
  host: localhost

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  host: <%= ENV["DB_HOST"] %>
